[book]
title = "æŠ˜è…¾æŠ€æœ¯ / HOME-NETWORK-NOTE ğŸš€"
description = "è®°å½•æ­å»ºå…¼é¡¾å­¦ä¹ å¨±ä¹çš„å®¶ç”¨ç½‘ç»œç¯å¢ƒçš„è¿‡ç¨‹ï¼ŒæŠ˜è…¾è¿‡çš„ä¸€äº›è½¯ç¡¬ä»¶å°ç»éªŒã€‚"
authors = ["soulteary"]
language = "en"
multilingual = false
src = "handbook"

[build]
build-dir = "../home-network-note-release"

[output.html]
git-repository-url="https://github.com/soulteary/Home-Network-Note"
edit-url-template="https://github.com/soulteary/Home-Network-Note/edit/main/{path}"
google-analytics = "G-RXQS80RJYV"

[output.html.search]
enable = false
